# Generated by Django 4.2 on 2024-05-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Слаг'),
        ),
    ]
