# Generated by Django 4.2 on 2024-05-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_emails', models.BooleanField(default=True, verbose_name='Отправка писем включена')),
            ],
            options={
                'verbose_name': 'Настройки email',
                'db_table': 'email_configurations',
            },
        ),
    ]
